#ifndef SDA_PLATFORM_CONSTS_H
#define SDA_PLATFORM_CONSTS_H

#define SDA_BASE_PIN_IN 0
#define SDA_BASE_PIN_OUT 1
#define SDA_BASE_PIN_ALT 2

#define SDA_BASE_PIN_NOPULL 0
#define SDA_BASE_PIN_PULLDOWN 1
#define SDA_BASE_PIN_PULLUP 1

#define INFO_WIDTH 600
#define INFO_HEIGHT 400

#define INFO_FB 1
#define MAIN_FB 0

#define SIM_X 67
#define SIM_Y 58

#define MIN_PCM_VOLUME_VALUE 5
#define MAX_PCM_VOLUME_VALUE 128

#endif
